set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(_MYCSGO_LLVM_MINGW_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.local-tools/toolchains/llvm-mingw-20260311-ucrt-ubuntu-22.04-x86_64")
set(_MYCSGO_NINJA "${CMAKE_CURRENT_LIST_DIR}/../../.local-tools/toolchains/ninja-linux/ninja")

set(CMAKE_C_COMPILER "${_MYCSGO_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${_MYCSGO_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${_MYCSGO_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_AR "${_MYCSGO_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-llvm-ar")
set(CMAKE_RANLIB "${_MYCSGO_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-llvm-ranlib")
set(CMAKE_MAKE_PROGRAM "${_MYCSGO_NINJA}" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${_MYCSGO_LLVM_MINGW_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

